/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LivestreamType = IDL.Variant({
  'Facebook' : IDL.Null,
  'YouTube' : IDL.Null,
  'Other' : IDL.Null,
});
export const Time = IDL.Int;
export const Livestream = IDL.Record({
  'updatedAt' : Time,
  'embedCode' : IDL.Text,
});
export const MemberProfile = IDL.Record({
  'displayName' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLivestream' : IDL.Func(
      [LivestreamType],
      [IDL.Opt(Livestream)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(MemberProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MemberProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveLivestream' : IDL.Func([LivestreamType, IDL.Text], [], []),
  'upsertMyProfile' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LivestreamType = IDL.Variant({
    'Facebook' : IDL.Null,
    'YouTube' : IDL.Null,
    'Other' : IDL.Null,
  });
  const Time = IDL.Int;
  const Livestream = IDL.Record({ 'updatedAt' : Time, 'embedCode' : IDL.Text });
  const MemberProfile = IDL.Record({
    'displayName' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLivestream' : IDL.Func(
        [LivestreamType],
        [IDL.Opt(Livestream)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(MemberProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MemberProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveLivestream' : IDL.Func([LivestreamType, IDL.Text], [], []),
    'upsertMyProfile' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };